boilerplate:
  showImports: true

variables:
  sdkImport: |
    using EulerApiSdk;
    using EulerApiSdk.Client;
  clientConstruction: |
    var client = new EulerStreamApiClient(
        host => host.AddTokens(new ApiKeyToken("$apiKey", ClientUtils.ApiKeyHeader.ApiKey)),
        baseAddress: "$baseUrl"
    );
  clientVar: client
  apiAccessPattern: dot

templatePath: ./wrapper.mustache

outputFormats:
  - md
  - json

apiClassMap:
  "TikTok LIVE": Webcast
  Accounts: Accounts
  Authentication: Authentication
  Analytics: Analytics
  Alerts: Alerts
  "Alert Targets": AlertTargets
  Captchas: Captchas

paramOverrides:
  global:
    account_id: $accountId
    alert_id: $alertId
    target_id: $targetId
