boilerplate:
  showImports: true

variables:
  sdkImport: |
    import (
    	"context"
    	eulerstream "github.com/EulerStream/Euler-Api-Sdk/sdk/go"
    )
  clientConstruction: |
    client := eulerstream.NewEulerStreamClient(
    	eulerstream.WithAPIKey("YOUR_API_KEY"),
    	eulerstream.WithServerURL("https://tiktok.eulerstream.com"),
    )
  clientVar: client
  apiAccessPattern: dot

templatePath: ./wrapper.mustache

outputFormats:
  - md
  - json

apiClassMap:
  "TikTok LIVE": Webcast
  Accounts: Accounts
  Authentication: Authentication
  Analytics: Analytics
  Alerts: Alerts
  "Alert Targets": AlertTargets
  Captchas: Captchas
