boilerplate:
  showImports: true

variables:
  sdkImport: "import EulerStreamApiClient from '@eulerstream/euler-api-sdk'"
  clientConstruction: "const client = new EulerStreamApiClient({ apiKey: '$apiKey', basePath: '$baseUrl' });"
  clientVar: client
  apiAccessPattern: dot

templatePath: ./wrapper.mustache

outputFormats:
  - md
  - json

apiClassMap:
  "TikTok LIVE": webcast
  Accounts: accounts
  Authentication: authentication
  Analytics: analytics
  Alerts: alerts
  "Alert Targets": alertTargets
  Captchas: captchas

paramOverrides:
  global:
    account_id: $accountId
